### PR TITLE
fix(explore): simplify display of sensor info to allow more displayed on map (PPT-1317)

### PR DESCRIPTION
**Pull request by MrYuion**

### CODE REVIEW

**Comment by w-le** [comment]
Cool it works and generally solves the problem, thank you.

Personally I think the ? icon should be changed to something else and that the dots could be smaller, but that will be an easy cosmetic customisation for any custom forks, so there is no urgency. We can discuss and reach an agreement on the cosmetics as a group, on the next weekly FE review call

Screenshot 2024-04-16 at 10 15 01 PM

**Comment by MrYuion** [comment]
I'm fine making them smaller though it might make them hard to click on touch devices.

**Comment by w-le** [comment]
> I'm fine making them smaller though it might make them hard to click on touch devices.

Ah yeah that's a good point

**Comment by w-le** [comment]
Let's change the ? icon to an i icon

**Comment by w-le** [comment]
let's make a small, non-urgent improvement such that the info balloon is never obscured by other dots

Screenshot 2024-04-18 at 1 04 36 PM

**Review by w-le — APPROVED** [review]
tested ok. additional small improvement requested

**Pull request merged**
