### PR TITLE
fix(assets): fix handling of clashes on edit (PROJ-658)

### PR DESCRIPTION
**Pull request by MrYuion**

### CODE REVIEW

**Comment by MrYuion** [comment]
* **#352** <a href="https://app.graphite.dev/github/pr/PlaceOS/user-interfaces/352?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MrYuion and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by w-le** [comment]
reviewed this with alex.

Currently this fix notifies the user AFTER the event is moved, which means that the user still needs to "guess and check" as they cannot know when the assets they need will be free, before moving the event. This guess and check strategy is not suitable as each time the event is moved all attendees will get an email notification of the new event time.

Alex has said that he will change this such that the user will be notified of any booking clashes just after they click the Confirm button but BEFORE the event is patched - i.e. when the user is still on the Event edit form. So this is still guess and check BUT prevents the event patch each time (which prevents the email notification to all attendees each time).

Also, the event save confirmation modal will list the booking clashes with a red outling, and show a red X instead of a green tick for the Assets section, lisitng each order and THEIR ITEMS like this, e.g.
image

**Review by w-le — APPROVED** [review]
was able to create an event with 2 asset orders (using up all 3 presenter remote) and then move that event to another day without the orders clashing with themselves. This was the particular scenario that was reported as a problem in the previous iteration so very good that this works smoothly now. 
I have not tested the many other editing/creation scenarios that can occur.

**Comment by w-le** [comment]
requesting further testing of this feature from @ksra08

**Comment by ksra-08** [comment]
Tested editing events with assets and it works fine.

**Comment by w-le** [comment]
Alex to resolve an issue found today where moving an event time causes 2 asset bookings of the same type of asset to clash with each other.

It appears that the asset Bookings requested overlapping IDs, even though there was availability to request unique ids (confirmed in concierge).

**Pull request merged**
